name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build-Project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment Variables
        run: |
          echo "HAXE_VERSION=4.3.4" >> $GITHUB_ENV
          echo "LIME_VERSION=7.9.0" >> $GITHUB_ENV
          echo "HXCPP_VERSION=4.2.1" >> $GITHUB_ENV
          echo "FORMAT_VERSION=3.5.0" >> $GITHUB_ENV
          echo "EMITTER_VERSION=3.0.0" >> $GITHUB_ENV
          echo "WINDOWS_BUILD_PATH=D:/a/BeatFusion/BeatFusion/bin/windows/bin" >> $GITHUB_ENV
          echo "HTML5_BUILD_PATH=D:/a/BeatFusion/BeatFusion/bin/html5/bin" >> $GITHUB_ENV

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - run: haxe -version

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=${{ env.HAXE_STD_PATH }}/.." >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          chmod +x .github/scripts/install_dependencies.sh
          .github/scripts/install_dependencies.sh

      - name: Build Projects
        run: |
          chmod +x .github/scripts/build_projects.sh
          .github/scripts/build_projects.sh

      - name: Upload Artifacts
        run: |
          chmod +x .github/scripts/upload_artifacts.sh
          .github/scripts/upload_artifacts.sh

      - name: Deploy
        if: always()
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: dimensionscape.bfengine.surge.sh
          project: ${{ env.HTML5_BUILD_PATH }}
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
